# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    types: [ closed ]
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
          
      - name: Build with Maven
        run: mvn package -B -Dmaven.test.skip

      # Ignore error so report can be created later
      - name: Test
        run: mvn test -B --fail-at-end

      # Process and Publish Test Report
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1